# Generated by Django 5.1.7 on 2025-04-04 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorProductCategory',
            new_name='VendorCategory',
        ),
        migrations.AlterUniqueTogether(
            name='affiliatereferrallink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='affiliatereferrallink',
            name='affiliate',
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_base',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='click_through_rate',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='paid_earnings',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='pending_earnings',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='total_referrals',
        ),
        migrations.RemoveField(
            model_name='product',
            name='affiliate_commission_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_discounted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='review',
            name='verified_purchase',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='payout_threshold',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='swift_code',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tax_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='AffiliateReferralLink',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
